export { batch } from './batch'
export { compareWith } from './compare-with'
export { functor } from './functor'
export { identity } from './identity'
export { negate } from './negate'
export { property } from './property'
export { replaceArrayContents } from './replace-array-contents'
